s=input(" Enter a string:")
print("Length of",s,"is",len(s))
print("String in lower case:",s.lower())
print("String in Upper case:",s.upper())
print("swapping of String Cases:",s.swapcase())
print("Capitalizing first charater:",s.capitalize())
print("capitalize first letter of all words:",s.title())
m=input(" Enter a string with * charaters:")
print("Striping the * charaters from the beginning :",m.lstrip('*'))
print("Striping the * charaters from the end :",m.rstrip('*'))
print("Striping the * charaters : ",m.strip('*'))
print("Maximum Charater of",s,"is",max(s))
print("Minimum Charater of",s,"is",min(s))
print("Center:",s.center(30,'*'))
print("Center:",s.center(30))
print(s.rjust(30, '*'))
print(s.rjust(30))
print("Zeros to fill width:",s.zfill(20))
print("Counting no i in the statment",s.count('i',0,10))
